# Generated by Django 4.2.7 on 2025-09-28 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the event', max_length=255)),
                ('event_type', models.CharField(choices=[('account_management', 'Account Management Event'), ('store_acquisition', 'Store Acquisition')], help_text='Type of the event', max_length=50)),
                ('start_date', models.DateField(help_text='Start date of the event')),
                ('end_date', models.DateField(help_text='End date of the event')),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number for the event', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('store_location', models.TextField(blank=True, help_text='Location details for Store Acquisition events', null=True)),
                ('store_phone_number', models.CharField(blank=True, help_text='Store contact phone number for Store Acquisition events', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the event was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the event was last updated')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the event is active')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['-created_at'],
            },
        ),
    ]
