# Generated by Django 4.2.7 on 2025-09-28 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the event', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Associated store for Account Management events', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='stores.store'),
        ),
    ]
