# Generated by Django 4.2.7 on 2025-09-28 08:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Store name', max_length=255, unique=True)),
                ('address', models.TextField(help_text='Store address')),
                ('town', models.CharField(help_text='Town or city', max_length=100)),
                ('country', models.CharField(help_text='Country', max_length=100)),
                ('county', models.CharField(blank=True, help_text='County or state', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'stores',
                'ordering': ['-created_at'],
            },
        ),
    ]
